version: '3.4'

# 開啟服務
services:
    #Consul 服務發現
    consul:
        image: consul
        container_name: ${CONSUL_HOST}
        ports:
            - 8500:8500
            - 8600:8600/udp
        command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
        networks:
            - lbbankend
    #MSSQL 資料庫
    mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        user: root
        ports: 
            - 11433:1433
        container_name: loadbalancemssql
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=*Paulwu1688
        volumes:
            - ./Data/MSSQL:/var/opt/mssql/data
        networks: 
            - lbbankend
    #網站一
    loadbalance.web1:
        image: ${DOCKER_REGISTRY-}loadbalanceweb
        container_name: lbweb1
        build:
            context: .
            dockerfile: LoadBalance.Web/Dockerfile
        environment:
            - dbserver=${DBSERVER}
            - dbname=${DBNAME} 
            - dbuser=${DBUSER} 
            - dbpw=${DBPW} 
            - webappmsg="我的第一個網站"
            - consulhost=${CONSUL_HOST}
        networks: 
            - lbbankend
        ports: 
            - 7414:80
        depends_on:
            - "mssql"
            - "consul"
    #網站二
    loadbalance.web2:
        image: ${DOCKER_REGISTRY-}loadbalanceweb
        container_name: lbweb2
        build:
            context: .
            dockerfile: LoadBalance.Web/Dockerfile
        environment:
            - dbserver=${DBSERVER}
            - dbname=${DBNAME} 
            - dbuser=${DBUSER} 
            - dbpw=${DBPW} 
            - webappmsg="我的第二個網站"
            - consulhost=${CONSUL_HOST}
        networks: 
            - lbbankend
        ports: 
            - 7415:80
        depends_on:
            - "mssql"
            - "consul"

    #網站三
    loadbalance.web3:
        image: ${DOCKER_REGISTRY-}loadbalanceweb
        container_name: lbweb3
        build:
            context: .
            dockerfile: LoadBalance.Web/Dockerfile
        environment:
            - dbserver=${DBSERVER}
            - dbname=${DBNAME} 
            - dbuser=${DBUSER} 
            - dbpw=${DBPW} 
            - webappmsg="我的第三個網站"
            - consulhost=${CONSUL_HOST}
        networks: 
            - lbbankend
        ports: 
            - 7416:80
        depends_on:
            - "mssql"
            - "consul"
    nginx:
        image:  nginx
        container_name: lbnginx
        networks:
            - lbbankend
        ports:
            - 7417:80
        volumes:
            - ./Data/NGINX/Config/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - "loadbalance.web1"
            - "loadbalance.web2"
            - "loadbalance.web3"

# 定義網路介面
networks:
    lbbankend:
        #若Docker中已經有此網路使用 external: true 直接使用原有網路
        #external: true 
        name: lbbankend